# Generated by Django 4.2 on 2024-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence_absence',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
