# Generated by Django 4.2 on 2024-09-03 11:26

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_presence_absence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence_absence',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
