# Generated by Django 4.2 on 2024-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_presence_absence_date_alter_score_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ons',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
