# Generated by Django 4.2 on 2024-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_score_ons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='date_for',
        ),
        migrations.AddField(
            model_name='score',
            name='creat_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
