# Generated by Django 4.2 on 2024-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_rename_date_score_date_for_score_creat_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence_absence',
            name='was',
        ),
        migrations.AddField(
            model_name='presence_absence',
            name='was_or_not_or',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent_unwarranted', 'غایب/غیر موجه'), ('absent_warranted', 'غایب/موجه')], max_length=50, null=True),
        ),
    ]
