# Generated by Django 4.2 on 2024-10-07 21:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_sum_emtiyazat_sum_final_alter_presence_absence_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence_absence',
            name='date',
            field=django_jalali.db.models.jDateField(default='null'),
            preserve_default=False,
        ),
    ]
