# Generated by Django 4.2 on 2024-07-02 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='شماره تلفن ')),
                ('owner', models.CharField(choices=[('itself', 'شخصی'), ('father', 'پدر'), ('mather', 'مادر')], max_length=6, verbose_name='مالکیت')),
                ('exta_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extra_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('adress', models.CharField(max_length=255, verbose_name='ادرس')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر ')),
                ('type', models.CharField(choices=[('اوپراتور', 'operator '), ('معلم', 'teacher '), ('student', 'دانش اموز')], max_length=50)),
                ('meli_cood', models.CharField(max_length=50, verbose_name='کد ملی')),
                ('sex', models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=50)),
                ('forign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
