# Generated by Django 4.2 on 2024-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='adress',
            field=models.CharField(max_length=500, verbose_name='ادرس'),
        ),
    ]
