# Generated by Django 4.2 on 2024-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0002_alter_extra_user_data_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_user_data',
            name='image',
            field=models.ImageField(null=True, upload_to='personality_picture/'),
        ),
    ]
