# Generated by Django 4.2 on 2024-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0003_extra_user_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='image',
            field=models.ImageField(default='personality_picture/boy.png', upload_to='personality_picture/'),
        ),
    ]
