# Generated by Django 4.2 on 2024-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0005_alter_extra_user_data_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='adress',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='extra_user_data',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='extra_user_data',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر '),
        ),
        migrations.AlterField(
            model_name='extra_user_data',
            name='meli_cood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='extra_user_data',
            name='sex',
            field=models.CharField(blank=True, choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extra_user_data',
            name='type',
            field=models.CharField(blank=True, choices=[('اوپراتور', 'operator '), ('معلم', 'teacher '), ('student', 'دانش اموز'), ('free student', 'مستمع ازاد')], max_length=50, null=True),
        ),
    ]
