# Generated by Django 4.2 on 2024-07-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0006_alter_extra_user_data_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='سن'),
        ),
    ]
