# Generated by Django 4.2 on 2024-07-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0007_alter_extra_user_data_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_user_data',
            name='father_name',
        ),
    ]
