# Generated by Django 4.2 on 2024-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0009_alter_extra_user_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='type',
            field=models.CharField(blank=True, choices=[('operator', 'اوپراتور'), ('teacher', 'معلم'), ('student', 'دانش اموز'), ('Guest', 'مهمان')], default='Guest', max_length=50, null=True),
        ),
    ]
