# Generated by Django 4.2 on 2024-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0010_alter_extra_user_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=50, null=True),
        ),
    ]
