# Generated by Django 4.2 on 2024-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0011_alter_extra_user_data_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=50, null=True),
        ),
    ]
