# Generated by Django 4.2 on 2024-08-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0012_alter_extra_user_data_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='exta_user_data',
            new_name='forign_key',
        ),
    ]
