# Generated by Django 4.2 on 2024-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0013_rename_exta_user_data_phone_forign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='owner',
            field=models.CharField(blank=True, choices=[('itself', 'شخصی'), ('father', 'پدر'), ('mather', 'مادر')], max_length=6, verbose_name='مالکیت'),
        ),
    ]
