# Generated by Django 4.2 on 2024-08-11 18:42

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('athentication', '0014_alter_phone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_data',
            name='age',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سن'),
        ),
    ]
