# Generated by Django 4.2 on 2024-08-15 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.PositiveIntegerField()),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_data', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='link_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_of_class', models.BooleanField()),
                ('klass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.klass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='klass',
            name='student',
            field=models.ManyToManyField(related_name='have_staudent', through='enroll.link_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
