# Generated by Django 4.2 on 2024-08-13 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.PositiveIntegerField()),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_data', django_jalali.db.models.jDateField()),
                ('student', models.ManyToManyField(related_name='have_staudent', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
