# Generated by Django 4.2 on 2024-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='klass',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='klass',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
